# System Parameters
api:
  host: 0.0.0.0
  port: 8000
  workers: 4
  timeout: 300  # seconds

performance:
  batch_size: 100
  parallel_operations: true
  cache_ciphertexts: true
  cache_ttl: 3600

limits:
  max_ciphertext_size: 10485760  # 10MB
  max_batch_size: 1000
  max_circuit_depth: 10
  max_noise_budget: 1280

noise_management:
  track_noise: true
  auto_bootstrap: true
  bootstrap_threshold: 0.8
  noise_estimation: conservative